### ISSUE TITLE
Couldn't build project

### ISSUE THREAD

**Issue by PlashSpeed-Aiman** [NerdyMusician/GAMMA#12]
MSB3327	Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	GAMMA	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	3425	

is there any way to resolve this issue?

**Comment by NerdyMusician** [comment]
Is this seen when just trying to build or when attempting to publish? I only see this error when attempting to publish via ClickOnce, which for releases I publish to folder since I don't sign GAMMA with a certificate.
